name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
            - ubuntu-latest
            # - windows-latest # disabled as we don't have bison/yacc available here!
            # - macos-latest # disabled as we don't have bison/yacc available here!
        target: 
            - x86_64-linux-musl
            - x86_64-windows
            - x86_64-macos
            - aarch64-macos

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: "0.14.0"

      - name: Build ${{ matrix.target }} on ${{ matrix.os }}
        run: |
          zig build -Dtarget=${{ matrix.target }} -Doptimize=ReleaseSafe

      - name: Upload disk image
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}_${{ matrix.os }}
          path: zig-out
          if-no-files-found: warn
          retention-days: 7
